import mongoose from 'mongoose';

const MessageSchema = new mongoose.Schema({
  role: {
    type: String,
    enum: ['user', 'assistant'],
    required: true
  },
  content: {
    type: String,
    required: true
  },
  timestamp: {
    type: Date,
    default: Date.now
  }
}, { _id: false });

const ChatSessionSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // Array of messages in this session
  messages: {
    type: [MessageSchema],
    default: []
  },
  // Session summary generated by AI after session ends
  sessionSummary: {
    type: String,
    default: null
  },
  // Severity rating (1-5) generated by AI
  severityRating: {
    type: Number,
    min: 1,
    max: 5,
    default: null
  },
  // Indicates if session is active or ended
  status: {
    type: String,
    enum: ['active', 'ended'],
    default: 'active'
  },
  // Emergency escalation triggered (boolean)
  escalationTriggered: {
    type: Boolean,
    default: false
  },
  // Timestamp when session started
  startedAt: {
    type: Date,
    default: Date.now
  },
  // Timestamp when session ended
  endedAt: {
    type: Date,
    default: null
  }
}, { timestamps: true });

export default mongoose.model('ChatSession', ChatSessionSchema);
